### ISSUE TITLE
Transparent Menu Background

### ISSUE THREAD

**Issue by Vlerrie** [AdamG100/TCAdmin-Discord-Inspired-V2#1]
Hi,

I'm guessing this is the theme on the Hyper Layer website. Found an issue when opening the site on mobile.

When logged into the Game Control Panel within a game service: when you swipe left the side menu (service menu) pops over the current interface but the background is transparent so it's kinda hard to read and click correctly.

The element id is #serviceicons and just needs a background-color.

![image](https://user-images.githubusercontent.com/23453902/192338078-a6a74ea7-98b8-4116-8207-d9bbab13c4e2.png)

**Comment by AdamG100** [comment]
Hi its not but I have fixed it.
